# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-03 13:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterKtpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=30, verbose_name='Nama Depan')),
                ('last_name', models.CharField(default=None, max_length=30, verbose_name='Nama Belakang')),
                ('no_hp', models.IntegerField(default=None, null=True, verbose_name='No. Handphone Aktif')),
                ('nik', models.IntegerField(default=None, null=True, verbose_name='NIK')),
                ('document', models.FileField(upload_to='Data_Pemohon', verbose_name='Upload Berkas')),
                ('status_proses', models.CharField(choices=[('Belum Diproses', 'Belum Diproses'), ('Sedang Diproses', 'Sedang Diproses'), ('Selesai', 'Selesai')], default='Belum Diproses', max_length=20)),
            ],
        ),
    ]
