# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-03 14:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_auto_20200203_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerktpmodel',
            name='document',
            field=models.FileField(blank=True, upload_to='Data_Pemohon/', verbose_name='Upload Berkas'),
        ),
    ]
