# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-04 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_auto_20200203_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerpanjangKtpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, default=None, max_length=30, verbose_name='Nama Depan')),
                ('last_name', models.CharField(blank=True, default=None, max_length=30, verbose_name='Nama Belakang')),
                ('no_hp', models.IntegerField(blank=True, default=None, null=True, verbose_name='No. Handphone Aktif')),
                ('document', models.FileField(blank=True, upload_to='Data_Pemohon/', verbose_name='Fotocopy KTP')),
                ('document1', models.FileField(blank=True, upload_to='Data_Pemohon/', verbose_name='Fotocopy KK')),
                ('status_proses', models.CharField(choices=[('Belum Diproses', 'Belum Diproses'), ('Sedang Diproses', 'Sedang Diproses'), ('Selesai', 'Selesai')], default='Belum Diproses', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='registerktpmodel',
            name='document1',
            field=models.FileField(blank=True, upload_to='Data_Pemohon/', verbose_name='Fotocopy Akta Kelahiran'),
        ),
        migrations.AlterField(
            model_name='registerktpmodel',
            name='document',
            field=models.FileField(blank=True, upload_to='Data_Pemohon/', verbose_name='Fotocopy KK'),
        ),
        migrations.AlterField(
            model_name='registerktpmodel',
            name='nik',
            field=models.IntegerField(default=None, null=True, verbose_name='NIK'),
        ),
        migrations.AlterField(
            model_name='registerktpmodel',
            name='no_hp',
            field=models.IntegerField(default=None, null=True, verbose_name='No. Handphone Aktif'),
        ),
    ]
