# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-04 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_auto_20200204_1640'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerktpmodel',
            name='nik',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='NIK'),
        ),
        migrations.AlterField(
            model_name='registerktpmodel',
            name='no_hp',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='No. Handphone Aktif'),
        ),
    ]
