# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-04 16:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_auto_20200204_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perpanjangktpmodel',
            name='document',
            field=models.FileField(blank=True, upload_to='Data_Pemohon/Perpanjang/', verbose_name='Fotocopy KTP yang telah habis masa berlakunya'),
        ),
        migrations.AlterField(
            model_name='perpanjangktpmodel',
            name='document1',
            field=models.FileField(blank=True, upload_to='Data_Pemohon/Perpanjang/', verbose_name='Fotocopy KK'),
        ),
        migrations.AlterField(
            model_name='registerktpmodel',
            name='document',
            field=models.FileField(blank=True, upload_to='Data_Pemohon/registrasi/', verbose_name='Fotocopy KK'),
        ),
        migrations.AlterField(
            model_name='registerktpmodel',
            name='document1',
            field=models.FileField(blank=True, upload_to='Data_Pemohon/registrasi/', verbose_name='Fotocopy Akta Kelahiran'),
        ),
    ]
