# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-04 16:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0009_auto_20200204_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='perpanjangktpmodel',
            old_name='document1',
            new_name='kk_perpanjang',
        ),
        migrations.RenameField(
            model_name='perpanjangktpmodel',
            old_name='document',
            new_name='ktp',
        ),
        migrations.RenameField(
            model_name='registerktpmodel',
            old_name='document1',
            new_name='akta',
        ),
        migrations.RenameField(
            model_name='registerktpmodel',
            old_name='document',
            new_name='kk',
        ),
    ]
