# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-05 12:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0011_auto_20200204_1655'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PerpanjangKtpModel',
        ),
    ]
