# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_delete_perpanjangktpmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerktpmodel',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='registerktpmodel',
            name='last_name',
        ),
        migrations.AddField(
            model_name='registerktpmodel',
            name='namleng',
            field=models.CharField(blank=True, default=None, max_length=30, verbose_name='Nama Lengkap'),
        ),
    ]
