# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 03:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0016_auto_20200205_1936'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerktpmodel',
            name='namleng',
        ),
    ]
