# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 03:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_remove_registerktpmodel_namleng'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerktpmodel',
            name='namleng',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Nama Lengkap'),
        ),
    ]
