# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 03:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0018_registerktpmodel_namleng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerktpmodel',
            name='akta',
            field=models.FileField(blank=True, upload_to='Data_Pemohon/registrasi/', verbose_name='Foto Akta Kelahiran'),
        ),
        migrations.AlterField(
            model_name='registerktpmodel',
            name='kk',
            field=models.FileField(blank=True, upload_to='Data_Pemohon/registrasi/', verbose_name='Foto KK'),
        ),
    ]
