# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0020_auto_20200205_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerktpmodel',
            name='status_proses',
            field=models.CharField(choices=[('1', 'Belum Diproses'), ('2', 'Sedang Diproses'), ('3', 'Selesai')], max_length=20),
        ),
    ]
