# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0022_auto_20200205_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerktpmodel',
            name='pesan',
            field=models.TextField(blank=True, default=None, max_length=255, null=True, verbose_name='Pesan'),
        ),
        migrations.AlterField(
            model_name='registerktpmodel',
            name='status_proses',
            field=models.CharField(choices=[('Belum Diproses', 'Belum Diproses'), ('Sedang Diproses', 'Sedang Diproses'), ('Selesai', 'Selesai')], default='Belum Proses', max_length=20),
        ),
    ]
