# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 16:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0024_auto_20200206_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerktpmodel',
            name='namleng',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Nama Lengkap'),
        ),
        migrations.AlterField(
            model_name='registerktpmodel',
            name='nik',
            field=models.IntegerField(blank=True, default=None, null=True, verbose_name='Nomor Induk Keluarga'),
        ),
    ]
