# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-02 03:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0003_auto_20180318_0741'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterKtpModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=30, null=True)),
                ('last_name', models.CharField(default=None, max_length=30, null=True)),
                ('nik', models.FloatField(default=None, null=True)),
                ('document', models.FileField(default=None, null=True, upload_to=b'Data_Pemohon')),
            ],
        ),
    ]
