# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-02 04:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0005_auto_20200202_0415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerktpmodel',
            name='nik',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
