# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-02 05:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user_profile', '0010_auto_20200202_0516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registerktpmodel',
            name='document',
            field=models.ImageField(default=django.utils.timezone.now, upload_to=b'Data_Pemohon', verbose_name=b'Upload Document'),
            preserve_default=False,
        ),
    ]
